---
title: "Analyse des données Iris"
author: "Menyssa Cherifa-Luron"
date: "2023-01-25"
output:
  word_document:
    toc: true
    toc_depth: 2
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, include=TRUE, message  = FALSE, warning=FALSE)
```

```{r chargement-librairie}

# ggplot2 pour les visualisations
library(ggplot2)
# dplyr pour la manipulation des données
library(dplyr)
# caret pour l'évaluation des performances
library(caret)
# pROC calcul de l'AUC
library(pROC)
```

## Chargement des données

```{r chargement-des-donnees}
# Chargement du jeu de données iris
data(iris)

# Affichage des premières lignes du jeu de données
head(iris)
```

## Visualisations

```{r visualisation-des-donnees}

# Boxplot
ggplot(iris, aes(x = Species, y = Sepal.Length)) +
  geom_boxplot() +
  labs(title = "Boxplot de la longueur du sépale par espèce",
       x = "Espèce",
       y = "Longueur du sépale") +
  theme_classic()


# Histogramme 
ggplot(iris, aes(x = Petal.Length, fill = Species)) +
  geom_histogram(binwidth = 0.2, position = "dodge") +
  labs(title = "Histogramme de la longueur du pétale par espèce",
       x = "Longueur du pétale",
       y = "Fréquence",
       fill = "Espèce") +
  theme_classic()
```
 
## Classification de l'espèce versicolor selon le sépale

```{r Modèle logistique}

# Sélection des variables pertinentes pour le modèle logistique
iris_logistic <- iris %>%
  select(Sepal.Length, Sepal.Width, Species)

# Conversion de la variable cible "Species" en variable binaire
iris_logistic$Species <- ifelse(iris_logistic$Species == "versicolor", 1, 0)

# Construction du modèle logistique
model <- glm(Species ~ Sepal.Length + Sepal.Width, 
             data = iris_logistic, 
             family = "binomial")
summary(model)
```

### Performances du modèle

```{r performance-modele}
# coefficients
round(exp(model$coefficients),2)

# intervalle de confiance à 95% des coefficients
round(exp(confint(model)),5)

# Prédictions
predictions <- predict(model, newdata = iris_logistic, 
                       type = "response")

# Choix du seuil de probabilité supérieur à 0.5 
predictions <- ifelse(predictions > 0.5, 1, 0)

predictions_class <- factor(predictions, 
                            labels = c("versicolor", "autres"),
                            levels = c(1,0))
observation_class <- factor(iris_logistic$Species, 
                            labels = c("versicolor", "autres"),
                            levels = c(1,0))
# Table de confusion
result <- confusionMatrix(predictions_class, observation_class, 
                          positive = "versicolor")
print(result)
# AUC
predictions <- predict(model, type = "response")

versicolor_ROC <- roc(observation_class, predictions,
                   plot=TRUE,
                   print.auc=TRUE,col="blue",
                   lwd =4,legacy.axes=TRUE,main="Aire sous la courbe ROC")

# intervalle de confiance 95% de l'auc
ci(versicolor_ROC)
```

### Predictions du modèle

```{r predictions-modele}

# Génération de 500 nouvelles valeurs de poids : wt
new_data <- data.frame(
  Sepal.Length = seq(min(iris_logistic$Sepal.Length),
                     max(iris_logistic$Sepal.Length),len = 500),
  Sepal.Width = seq(min(iris_logistic$Sepal.Width), 
                    max(iris_logistic$Sepal.Width),len = 500)
 )

# Prédictions de am associées aux nouvelles valeurs de sépales
new_data$espece <- predict(model, new_data, type="response")
new_data$espece  <- ifelse(new_data$espece > 0.5, "versicolor","autres")


ggplot(new_data, aes(x = espece, y = Sepal.Length))+
  geom_boxplot() +
  labs(title = "Boxplot de longueur du sépale par espèce",
       x = "Espèce",
       y = "Longueur du sépale") +
  theme_classic()

ggplot(new_data, aes(x = espece, y = Sepal.Width))+
  geom_boxplot() +
  labs(title = "Boxplot de largeur du sépale par espèce",
       x = "Espèce",
       y = "Largeur du sépale") +
  theme_classic()

  
```








